const errors = {
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  KEY_EXISTED: 'KEY_EXISTED',
  NOT_TOKEN: 'NOT_TOKEN',
  NOT_EXIST: 'NOT_EXIST',
  DB_CONNECTION_ORGNIZATION: 'DB_CONNECTION_ORGNIZATION',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  REACHED_MAX_STATIONS: 'REACHED_MAX_STATIONS',
  NETWORK_ERROR: 'NETWORK_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INVALID_RTSP: 'INVALID_RTSP',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR'
}
export default errors
